# Generated by Django 3.1.5 on 2021-01-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_auto_20210113_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='descriptio',
            new_name='description',
        ),
    ]
