# Generated by Django 3.1.5 on 2021-01-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_auto_20210113_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('rtype', models.CharField(max_length=10)),
                ('nos', models.IntegerField()),
                ('event', models.IntegerField()),
            ],
        ),
    ]
