# Generated by Django 3.1.5 on 2021-01-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0004_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='nos',
            new_name='participants',
        ),
    ]
