# Generated by Django 3.1.5 on 2021-01-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0006_auto_20210116_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='event',
            new_name='event_id',
        ),
    ]
