# Generated by Django 3.1.5 on 2021-02-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0007_auto_20210116_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endtime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='fromtime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='totime',
            field=models.TimeField(),
        ),
    ]
